# Generated by Django 5.0.2 on 2024-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_companyreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jobtitle', models.CharField(max_length=20)),
                ('worktype', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('jobtype', models.CharField(max_length=20)),
            ],
        ),
    ]
